import type { AdminRouteMetadata } from "../routes/admin-route-metadata";

export const baseRouteManifest: AdminRouteMetadata[] = [
  {
    routeCode: "dashboard",
    path: "/",
    titleI18nKey: "routes.dashboard",
    menuVisible: true,
    sortOrder: 10,
  },
  {
    routeCode: "system.organizations",
    path: "/system/organizations",
    titleI18nKey: "routes.system.organizations",
    requiredPermission: "organization:view",
    menuVisible: true,
    sortOrder: 100,
  },
  {
    routeCode: "system.users",
    path: "/system/users",
    titleI18nKey: "routes.system.users",
    requiredPermission: "user:view",
    menuVisible: true,
    sortOrder: 110,
  },
  {
    routeCode: "system.roles",
    path: "/system/roles",
    titleI18nKey: "routes.system.roles",
    requiredPermission: "role:view",
    menuVisible: true,
    sortOrder: 120,
  },
  {
    routeCode: "system.permissions",
    path: "/system/permissions",
    titleI18nKey: "routes.system.permissions",
    requiredPermission: "permission:view",
    menuVisible: true,
    sortOrder: 130,
  },
  {
    routeCode: "system.menus",
    path: "/system/menus",
    titleI18nKey: "routes.system.menus",
    requiredPermission: "menu:view",
    menuVisible: true,
    sortOrder: 140,
  },
  {
    routeCode: "system.config",
    path: "/system/config",
    titleI18nKey: "routes.system.config",
    requiredPermission: "system-config:view",
    menuVisible: true,
    sortOrder: 150,
  },
  {
    routeCode: "system.dictionaries",
    path: "/system/dictionaries",
    titleI18nKey: "routes.system.dictionaries",
    requiredPermission: "dictionary:view",
    menuVisible: true,
    sortOrder: 160,
  },
  {
    routeCode: "system.i18nMessages",
    path: "/system/i18n-messages",
    titleI18nKey: "routes.system.i18nMessages",
    requiredPermission: "i18n:view",
    menuVisible: true,
    sortOrder: 165,
  },
  {
    routeCode: "system.files",
    path: "/system/files",
    titleI18nKey: "routes.system.files",
    requiredPermission: "file:view",
    menuVisible: true,
    sortOrder: 170,
  },
  {
    routeCode: "notifications.announcements",
    path: "/notifications/announcements",
    titleI18nKey: "routes.notifications.announcements",
    requiredPermission: "announcement:view",
    menuVisible: true,
    sortOrder: 200,
  },
  {
    routeCode: "notifications.in-app",
    path: "/notifications/in-app",
    titleI18nKey: "routes.notifications.inApp",
    requiredPermission: "notification:view",
    menuVisible: true,
    sortOrder: 210,
  },
  {
    routeCode: "notifications.templates",
    path: "/notifications/templates",
    titleI18nKey: "routes.notifications.templates",
    requiredPermission: "notification-template:view",
    menuVisible: true,
    sortOrder: 215,
  },
  {
    routeCode: "notifications.webhooks",
    path: "/notifications/webhooks",
    titleI18nKey: "routes.notifications.webhooks",
    requiredPermission: "webhook:view",
    menuVisible: true,
    sortOrder: 220,
  },
  {
    routeCode: "operations.online-users",
    path: "/operations/online-users",
    titleI18nKey: "routes.operations.onlineUsers",
    requiredPermission: "online-user:view",
    menuVisible: true,
    sortOrder: 300,
  },
  {
    routeCode: "operations.scheduler",
    path: "/operations/scheduler",
    titleI18nKey: "routes.operations.scheduler",
    requiredPermission: "job:view",
    menuVisible: true,
    sortOrder: 310,
  },
  {
    routeCode: "operations.import-export",
    path: "/operations/import-export",
    titleI18nKey: "routes.operations.importExport",
    requiredPermission: "import-export:view",
    menuVisible: true,
    sortOrder: 320,
  },
  {
    routeCode: "logs.login",
    path: "/logs/login",
    titleI18nKey: "routes.logs.login",
    requiredPermission: "login-log:view",
    menuVisible: true,
    sortOrder: 400,
  },
  {
    routeCode: "logs.operation",
    path: "/logs/operation",
    titleI18nKey: "routes.logs.operation",
    requiredPermission: "operation-log:view",
    menuVisible: true,
    sortOrder: 401,
  },
  {
    routeCode: "logs.access",
    path: "/logs/access",
    titleI18nKey: "routes.logs.access",
    requiredPermission: "access-log:view",
    menuVisible: true,
    sortOrder: 402,
  },
  {
    routeCode: "logs.api",
    path: "/logs/api",
    titleI18nKey: "routes.logs.api",
    requiredPermission: "api-log:view",
    menuVisible: true,
    sortOrder: 403,
  },
  {
    routeCode: "logs.exception",
    path: "/logs/exception",
    titleI18nKey: "routes.logs.exception",
    requiredPermission: "exception-log:view",
    menuVisible: true,
    sortOrder: 404,
  },
  {
    routeCode: "logs.security",
    path: "/logs/security",
    titleI18nKey: "routes.logs.security",
    requiredPermission: "security-log:view",
    menuVisible: true,
    sortOrder: 405,
  },
  {
    routeCode: "logs.scheduler",
    path: "/logs/scheduler",
    titleI18nKey: "routes.logs.scheduler",
    requiredPermission: "scheduler-log:view",
    menuVisible: true,
    sortOrder: 406,
  },
  {
    routeCode: "logs.files",
    path: "/logs/files",
    titleI18nKey: "routes.logs.files",
    requiredPermission: "file-log:view",
    menuVisible: true,
    sortOrder: 407,
  },
  {
    routeCode: "account.profile",
    path: "/account/profile",
    titleI18nKey: "routes.account.profile",
    menuVisible: true,
    sortOrder: 500,
  },
  {
    routeCode: "account.password",
    path: "/account/password",
    titleI18nKey: "routes.account.password",
    menuVisible: true,
    sortOrder: 510,
  },
  {
    routeCode: "account.settings",
    path: "/account/settings",
    titleI18nKey: "routes.account.settings",
    menuVisible: true,
    sortOrder: 520,
  },
];
