export type ApiPermissionLogLevel = "none" | "basic" | "request" | "request_response";

export type BaseApiPermissionManifestEntry = {
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  path: string;
  code: string;
  description: string;
  module: string;
  requiredPermission?: string;
  logLevel: ApiPermissionLogLevel;
  public: boolean;
};

export const baseApiPermissionManifest: BaseApiPermissionManifestEntry[] = [
  {
    method: "GET",
    path: "/api/health",
    code: "api.health.view",
    description: "Health check",
    module: "observability",
    logLevel: "none",
    public: true,
  },
  {
    method: "GET",
    path: "/api/metrics",
    code: "api.metrics.view",
    description: "Metrics endpoint placeholder",
    module: "observability",
    logLevel: "none",
    public: true,
  },
  {
    method: "GET",
    path: "/api/openapi.json",
    code: "api.openapi.view",
    description: "OpenAPI document for implemented APIs",
    module: "documentation",
    logLevel: "none",
    public: true,
  },
  {
    method: "GET",
    path: "/api/initialization/status",
    code: "api.initialization.status",
    description: "Check initialization status",
    module: "initialization",
    logLevel: "basic",
    public: true,
  },
  {
    method: "POST",
    path: "/api/initialization/setup",
    code: "api.initialization.setup",
    description: "Run first-start initialization setup",
    module: "initialization",
    logLevel: "request",
    public: true,
  },
  {
    method: "GET",
    path: "/api/setup/status",
    code: "api.setup.status",
    description: "PRD-compatible initialization status alias",
    module: "initialization",
    logLevel: "basic",
    public: true,
  },
  {
    method: "POST",
    path: "/api/setup/initialize",
    code: "api.setup.initialize",
    description: "PRD-compatible first-start initialization alias",
    module: "initialization",
    logLevel: "request",
    public: true,
  },
  {
    method: "POST",
    path: "/api/auth/login",
    code: "api.auth.login",
    description: "Username and password login",
    module: "auth",
    logLevel: "request",
    public: true,
  },
  {
    method: "POST",
    path: "/api/auth/refresh",
    code: "api.auth.refresh",
    description: "Refresh access token from refresh-token cookie",
    module: "auth",
    logLevel: "basic",
    public: true,
  },
  {
    method: "GET",
    path: "/api/auth/me",
    code: "api.auth.me",
    description: "Get current user profile, organization context, and permissions summary",
    module: "auth",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/auth/logout",
    code: "api.auth.logout",
    description: "Logout and revoke current session",
    module: "auth",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/auth/change-password",
    code: "api.auth.change-password",
    description: "Change current user's password",
    module: "auth",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/context/current-organization",
    code: "api.context.current-organization.switch",
    description: "Switch current organization and refresh permission context",
    module: "auth",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/auth/current-organization",
    code: "api.auth.current-organization.switch",
    description: "Switch current organization and refresh permission context",
    module: "auth",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/context/organizations",
    code: "api.context.organizations.list",
    description: "List organizations available to the current user",
    module: "auth",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/context/permissions",
    code: "api.context.permissions",
    description: "Get current permission and menu context",
    module: "auth",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions/effective",
    code: "api.permissions.effective",
    description: "Get effective permissions for the current user context",
    module: "auth",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/online-users",
    code: "api.online-users.view",
    description: "View online users",
    module: "auth",
    requiredPermission: "online-user:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/profile",
    code: "api.profile.view",
    description: "Get current user's personal profile and preferences",
    module: "profile",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/profile",
    code: "api.profile.update",
    description: "Update allowed personal profile fields",
    module: "profile",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/profile/preferences",
    code: "api.profile.preferences.update",
    description: "Update current user's UI preferences",
    module: "profile",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/profile/avatar",
    code: "api.profile.avatar.update",
    description: "Change current user's avatar file reference",
    module: "profile",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/organizations/tree",
    code: "api.organizations.tree",
    description: "View organization tree",
    module: "organizations",
    requiredPermission: "organization:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/organizations/config/depth",
    code: "api.organizations.depth.get",
    description: "Get organization maximum depth configuration",
    module: "organizations",
    requiredPermission: "organization:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/organizations/config/depth",
    code: "api.organizations.depth.update",
    description: "Update organization maximum depth configuration",
    module: "organizations",
    requiredPermission: "organization:depth:configure",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/organizations",
    code: "api.organizations.create",
    description: "Create organization",
    module: "organizations",
    requiredPermission: "organization:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/organizations/:id",
    code: "api.organizations.detail",
    description: "View organization detail",
    module: "organizations",
    requiredPermission: "organization:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/organizations/:id",
    code: "api.organizations.update",
    description: "Update organization",
    module: "organizations",
    requiredPermission: "organization:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/organizations/:id/disable",
    code: "api.organizations.disable",
    description: "Disable organization and descendants",
    module: "organizations",
    requiredPermission: "organization:disable",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/organizations/:id/enable",
    code: "api.organizations.enable",
    description: "Enable organization",
    module: "organizations",
    requiredPermission: "organization:enable",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/organizations/:id",
    code: "api.organizations.delete",
    description: "Soft delete organization",
    module: "organizations",
    requiredPermission: "organization:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/users",
    code: "api.users.list",
    description: "View users",
    module: "users",
    requiredPermission: "user:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users",
    code: "api.users.create",
    description: "Create user",
    module: "users",
    requiredPermission: "user:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/users/:id",
    code: "api.users.detail",
    description: "View user detail",
    module: "users",
    requiredPermission: "user:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/users/:id",
    code: "api.users.update",
    description: "Update user",
    module: "users",
    requiredPermission: "user:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/disable",
    code: "api.users.disable",
    description: "Disable user",
    module: "users",
    requiredPermission: "user:disable",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/enable",
    code: "api.users.enable",
    description: "Enable user",
    module: "users",
    requiredPermission: "user:enable",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/lock",
    code: "api.users.lock",
    description: "Lock user",
    module: "users",
    requiredPermission: "user:lock",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/unlock",
    code: "api.users.unlock",
    description: "Unlock user",
    module: "users",
    requiredPermission: "user:unlock",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/reset-password",
    code: "api.users.password.reset",
    description: "Administrator resets user password",
    module: "users",
    requiredPermission: "user:password:reset",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/users/:id",
    code: "api.users.delete",
    description: "Soft delete user",
    module: "users",
    requiredPermission: "user:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/users/:id/organizations",
    code: "api.users.organizations.list",
    description: "View user organization role bindings",
    module: "users",
    requiredPermission: "user:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/users/:id/organizations",
    code: "api.users.organizations.assign",
    description: "Assign user to organization with role",
    module: "users",
    requiredPermission: "user:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/users/:id/organizations/:organizationId",
    code: "api.users.organizations.remove",
    description: "Remove user organization role binding",
    module: "users",
    requiredPermission: "user:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/roles",
    code: "api.roles.list",
    description: "View roles",
    module: "roles",
    requiredPermission: "role:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/roles",
    code: "api.roles.create",
    description: "Create role",
    module: "roles",
    requiredPermission: "role:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/roles/:id",
    code: "api.roles.detail",
    description: "View role detail",
    module: "roles",
    requiredPermission: "role:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/roles/:id",
    code: "api.roles.update",
    description: "Update role",
    module: "roles",
    requiredPermission: "role:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/roles/:id/enable",
    code: "api.roles.enable",
    description: "Enable role",
    module: "roles",
    requiredPermission: "role:status:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/roles/:id/disable",
    code: "api.roles.disable",
    description: "Disable role",
    module: "roles",
    requiredPermission: "role:status:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/roles/:id",
    code: "api.roles.delete",
    description: "Soft delete role",
    module: "roles",
    requiredPermission: "role:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/roles/:id/copy",
    code: "api.roles.copy",
    description: "Copy role and permission configuration",
    module: "roles",
    requiredPermission: "role:copy",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/roles/:id/permissions",
    code: "api.roles.permissions.view",
    description: "View role permission configuration",
    module: "roles",
    requiredPermission: "role:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PUT",
    path: "/api/roles/:id/permissions",
    code: "api.roles.permissions.update",
    description: "Update role permissions",
    module: "roles",
    requiredPermission: "role:permissions:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/roles/:id/data-permissions",
    code: "api.roles.data-permissions.view",
    description: "View role data permission rules",
    module: "roles",
    requiredPermission: "role:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PUT",
    path: "/api/roles/:id/data-permissions",
    code: "api.roles.data-permissions.update",
    description: "Update role data permission rules",
    module: "roles",
    requiredPermission: "role:permissions:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/roles/:id/field-permissions",
    code: "api.roles.field-permissions.view",
    description: "View role field permission rules",
    module: "roles",
    requiredPermission: "role:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PUT",
    path: "/api/roles/:id/field-permissions",
    code: "api.roles.field-permissions.update",
    description: "Update role field permission rules",
    module: "roles",
    requiredPermission: "role:permissions:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions",
    code: "api.permissions.list",
    description: "View permissions",
    module: "permissions",
    requiredPermission: "permission:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions/tree",
    code: "api.permissions.tree",
    description: "View virtual permission tree derived from flat permission metadata",
    module: "permissions",
    requiredPermission: "permission:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions/user-overrides/:userId",
    code: "api.permissions.user-overrides.view",
    description: "View user permission overrides",
    module: "permissions",
    requiredPermission: "permission:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PUT",
    path: "/api/permissions/user-overrides/:userId",
    code: "api.permissions.user-overrides.update",
    description: "Update user permission overrides",
    module: "permissions",
    requiredPermission: "permission:sync",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/permissions/sync",
    code: "api.permissions.sync",
    description: "Sync permission and API permission manifests",
    module: "permissions",
    requiredPermission: "permission:sync",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions/api",
    code: "api.permissions.api.list",
    description: "Query API permission identifiers",
    module: "permissions",
    requiredPermission: "permission:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/permissions/api/sync",
    code: "api.permissions.api.sync",
    description: "Sync API permission identifiers",
    module: "permissions",
    requiredPermission: "permission:api:sync",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/permissions/manifest",
    code: "api.permissions.manifest",
    description: "Preview generated permission manifest",
    module: "permissions",
    requiredPermission: "permission:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/routes/manifest",
    code: "api.routes.manifest",
    description: "View frontend route manifest",
    module: "routes",
    requiredPermission: "route:manifest:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/routes/sync",
    code: "api.routes.sync",
    description: "Sync frontend route manifest metadata",
    module: "routes",
    requiredPermission: "route:sync",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/menus/tree",
    code: "api.menus.tree",
    description: "View menu tree",
    module: "menus",
    requiredPermission: "menu:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/menus",
    code: "api.menus.create",
    description: "Create menu",
    module: "menus",
    requiredPermission: "menu:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/menus/:id",
    code: "api.menus.update",
    description: "Update menu",
    module: "menus",
    requiredPermission: "menu:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/menus/:id",
    code: "api.menus.delete",
    description: "Delete menu",
    module: "menus",
    requiredPermission: "menu:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "PUT",
    path: "/api/menus/:id/api-bindings",
    code: "api.menus.api-bindings.update",
    description: "Bind API permission identifiers to a menu",
    module: "menus",
    requiredPermission: "menu:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/system-config",
    code: "api.system-config.list",
    description: "List system configuration items",
    module: "system-config",
    requiredPermission: "system-config:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/system-config/:key",
    code: "api.system-config.update",
    description: "Update a system configuration value",
    module: "system-config",
    requiredPermission: "system-config:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/dictionary-types",
    code: "api.dictionary-types.list",
    description: "List dictionary types",
    module: "dictionaries",
    requiredPermission: "dictionary:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/dictionary-types",
    code: "api.dictionary-types.create",
    description: "Create dictionary type",
    module: "dictionaries",
    requiredPermission: "dictionary:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/dictionary-types/:id",
    code: "api.dictionary-types.update",
    description: "Update dictionary type",
    module: "dictionaries",
    requiredPermission: "dictionary:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/dictionary-types/:id/items",
    code: "api.dictionary-items.list",
    description: "List dictionary items",
    module: "dictionaries",
    requiredPermission: "dictionary:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/dictionary-types/:id/items",
    code: "api.dictionary-items.create",
    description: "Create dictionary item",
    module: "dictionaries",
    requiredPermission: "dictionary:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/dictionary-items/:id",
    code: "api.dictionary-items.update",
    description: "Update dictionary item",
    module: "dictionaries",
    requiredPermission: "dictionary:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/i18n/messages",
    code: "api.i18n.messages.list",
    description: "List i18n messages",
    module: "i18n",
    requiredPermission: "i18n:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/i18n/messages/:id",
    code: "api.i18n.messages.update",
    description: "Update i18n message",
    module: "i18n",
    requiredPermission: "i18n:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/login",
    code: "api.logs.login.list",
    description: "View login logs",
    module: "logs",
    requiredPermission: "login-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/operation",
    code: "api.logs.operation.list",
    description: "View operation logs",
    module: "logs",
    requiredPermission: "operation-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/access",
    code: "api.logs.access.list",
    description: "View access logs",
    module: "logs",
    requiredPermission: "access-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/api",
    code: "api.logs.api.list",
    description: "View API call logs",
    module: "logs",
    requiredPermission: "api-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/exception",
    code: "api.logs.exception.list",
    description: "View exception logs",
    module: "logs",
    requiredPermission: "exception-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/security",
    code: "api.logs.security.list",
    description: "View security logs",
    module: "logs",
    requiredPermission: "security-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/jobs",
    code: "api.logs.jobs.list",
    description: "View scheduler execution logs",
    module: "logs",
    requiredPermission: "scheduler-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/logs/files",
    code: "api.logs.files.list",
    description: "View file operation logs",
    module: "logs",
    requiredPermission: "file-log:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/logs/export",
    code: "api.logs.export",
    description: "Create async CSV log export task",
    module: "logs",
    requiredPermission: "log:export",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/files",
    code: "api.files.list",
    description: "View file list",
    module: "files",
    requiredPermission: "file:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/files/upload",
    code: "api.files.upload",
    description: "Upload file through configured storage adapter",
    module: "files",
    requiredPermission: "file:upload",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/files/:id",
    code: "api.files.detail",
    description: "View file metadata",
    module: "files",
    requiredPermission: "file:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/files/:id/download",
    code: "api.files.download",
    description: "Download file after permission check",
    module: "files",
    requiredPermission: "file:download",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/files/:id/preview",
    code: "api.files.preview",
    description: "Preview image file after permission check",
    module: "files",
    requiredPermission: "file:preview",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/files/:id/references",
    code: "api.files.references",
    description: "View file reference relationships",
    module: "files",
    requiredPermission: "file:references:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/files/:id",
    code: "api.files.delete",
    description: "Delete or invalidate file",
    module: "files",
    requiredPermission: "file:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/announcements",
    code: "api.announcements.list",
    description: "View announcements",
    module: "announcements",
    requiredPermission: "announcement:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/announcements",
    code: "api.announcements.create",
    description: "Create announcement",
    module: "announcements",
    requiredPermission: "announcement:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/announcements/:id",
    code: "api.announcements.update",
    description: "Update announcement",
    module: "announcements",
    requiredPermission: "announcement:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/announcements/:id/publish",
    code: "api.announcements.publish",
    description: "Publish announcement",
    module: "announcements",
    requiredPermission: "announcement:publish",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/announcements/:id/unpublish",
    code: "api.announcements.unpublish",
    description: "Unpublish announcement",
    module: "announcements",
    requiredPermission: "announcement:publish",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/notifications",
    code: "api.notifications.list",
    description: "View current user's in-app notifications",
    module: "notifications",
    requiredPermission: "notification:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/notifications/:id/read",
    code: "api.notifications.read",
    description: "Mark notification read",
    module: "notifications",
    requiredPermission: "notification:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/notifications/:id/archive",
    code: "api.notifications.archive",
    description: "Archive notification",
    module: "notifications",
    requiredPermission: "notification:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/notifications/:id",
    code: "api.notifications.delete",
    description: "Delete notification",
    module: "notifications",
    requiredPermission: "notification:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/notifications/email/test",
    code: "api.notifications.email.test",
    description: "Send a test email notification from an email template",
    module: "notifications",
    requiredPermission: "notification-template:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/notification-templates",
    code: "api.notification-templates.list",
    description: "View notification templates",
    module: "notifications",
    requiredPermission: "notification-template:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/email-deliveries",
    code: "api.email-deliveries.list",
    description: "View reliable email delivery history",
    module: "notifications",
    requiredPermission: "notification:email-delivery:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/email-deliveries/:id",
    code: "api.email-deliveries.detail",
    description: "View reliable email delivery attempts",
    module: "notifications",
    requiredPermission: "notification:email-delivery:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/notification-templates",
    code: "api.notification-templates.create",
    description: "Create notification template",
    module: "notifications",
    requiredPermission: "notification-template:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/notification-templates/:id",
    code: "api.notification-templates.update",
    description: "Update notification template",
    module: "notifications",
    requiredPermission: "notification-template:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/webhooks",
    code: "api.webhooks.list",
    description: "View webhook subscriptions",
    module: "webhooks",
    requiredPermission: "webhook:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/webhooks",
    code: "api.webhooks.create",
    description: "Create webhook subscription",
    module: "webhooks",
    requiredPermission: "webhook:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/webhooks/:id",
    code: "api.webhooks.update",
    description: "Update webhook subscription",
    module: "webhooks",
    requiredPermission: "webhook:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "DELETE",
    path: "/api/webhooks/:id",
    code: "api.webhooks.delete",
    description: "Delete webhook subscription",
    module: "webhooks",
    requiredPermission: "webhook:delete",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/webhook-event-types",
    code: "api.webhook-event-types.list",
    description: "View the controlled webhook event catalog",
    module: "webhooks",
    requiredPermission: "webhook:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/webhook-deliveries",
    code: "api.webhook-deliveries.list",
    description: "View webhook delivery history",
    module: "webhooks",
    requiredPermission: "webhook:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/webhook-deliveries/:id",
    code: "api.webhook-deliveries.detail",
    description: "View webhook delivery attempts",
    module: "webhooks",
    requiredPermission: "webhook:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "GET",
    path: "/api/scheduled-tasks",
    code: "api.scheduled-tasks.list",
    description: "View scheduled tasks",
    module: "jobs",
    requiredPermission: "job:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/scheduled-tasks",
    code: "api.scheduled-tasks.create",
    description: "Create scheduled task",
    module: "jobs",
    requiredPermission: "job:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "PATCH",
    path: "/api/scheduled-tasks/:id",
    code: "api.scheduled-tasks.update",
    description: "Update scheduled task",
    module: "jobs",
    requiredPermission: "job:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/scheduled-tasks/:id/enable",
    code: "api.scheduled-tasks.enable",
    description: "Enable scheduled task",
    module: "jobs",
    requiredPermission: "job:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/scheduled-tasks/:id/disable",
    code: "api.scheduled-tasks.disable",
    description: "Disable scheduled task",
    module: "jobs",
    requiredPermission: "job:update",
    logLevel: "request",
    public: false,
  },
  {
    method: "POST",
    path: "/api/scheduled-tasks/:id/run",
    code: "api.scheduled-tasks.run",
    description: "Manually enqueue scheduled task run",
    module: "jobs",
    requiredPermission: "job:run",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/import-export/tasks",
    code: "api.import-export.tasks.list",
    description: "View import/export task list",
    module: "import-export",
    requiredPermission: "import-export:view",
    logLevel: "basic",
    public: false,
  },
  {
    method: "POST",
    path: "/api/import-export/export",
    code: "api.import-export.export.create",
    description: "Create async CSV export task",
    module: "import-export",
    requiredPermission: "import-export:create",
    logLevel: "request",
    public: false,
  },
  {
    method: "GET",
    path: "/api/import-export/tasks/:id",
    code: "api.import-export.tasks.detail",
    description: "View import/export task detail",
    module: "import-export",
    requiredPermission: "import-export:view",
    logLevel: "basic",
    public: false,
  },
];
